### ISSUE TITLE
ROADMAP.md

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#22]
## Phase 1
- [x] 컨셉 기획 (README.md)
- [x] 기본기능구현
- [x] 기본디비구현
- [x] 이슈
- [x] 마크다운
- [x] 물흐르듯 넘어간 ORM
## Phase 2
- [x] DB Migration
- [x] 기능 연결
- [x] 간단 웹
- [x] 설정 추출
- [x] 코드리뷰
- [x] 울며 겨자맛 javascript먹기 시작
## Phase 3  <-- Now
- [x] 개발 메뉴얼 제작
- [ ] 웹 페이지 제작 [TODO]
- [x] 기능 별 파일 나누기
- [x] Flake8 코드 품질 관리
- [x] 로그인 가능
- [x] 파일 업로드 가능
- [ ] 알파 서비스 시작 [TODO]
- [x] 브랜치 개발 시작
- [x] 페어프로그래밍 해봄
- [x] 첫 머지
- [x] 첫 컨플릭트
## Phase 4
- [ ] 로드맵 제공을 통한 사기 증진
- [ ] 예쁜 코드베이스를 통한 개발자 호객
- [ ] 초보자를 위한 쉬운 이슈 모아두기
- [x] PHP구림/Spring 재미없음 설파
- [ ] 문서 꾸미기
- [x] 코드 리뷰 가능한 사람 3+명 확보 (민호 광희 민교)
- [ ] 문서 잘정리하는 Technical Writer 고용
- [ ] 파이썬 패키지로 제작 (폴더구조 도입)
- [ ] 배포 가능한 설정
- [ ] 코드리뷰시 자동 알파 서비스를 통한 공개처형
## Phase 5
- [ ] 배포가능한 파이썬 패키지
- [ ] 배포가능한 파이썬 패키지를 통한 pex 배포 (PyPi? 개인구축가능?)
- [ ] 베타 서비스 with 개강
- [ ] 그룹(업적) 제공
- [ ] 릴리즈 깃허브 계정으로 프로젝트 이관
- [ ] Pull request 리뷰
- [ ] 운영팀 꾸리고 밤낮없이 푸시보내기
- [ ] 갓 코드 리뷰 + 베스트 고민해결 정리
## Phase 6+ (Party)
- [ ] 기획안 작성법
- [ ] 봐줄만한 UI
  ...
- [ ] 인증기능 제공
- [ ] 검색기능 제공
- [ ] 다이나믹 UI
  ...
## Phase n
- [ ] 릴리즈 로그인 서버
- [ ] 릴리즈 서버 증설
## Phase n+1
- [ ] 릴리즈 로그인 서버를 통한 쉬운 웹 개발 템플릿 제공
## P hase n+m (이때 n>m)
- [ ] 르네상스+_+
- 빠진거: 테스트, 배포방법 설명, 시간관리, 디자인, 자신감 고취, 새 서버 관리자, MySQL구축매뉴얼, 쉬운 배포헬퍼 패키지

**Comment by minhoryang** [comment]
모바일이라 너무 힘드네요 ㅠㅠㅠㅠ
@jmg7173 @juice500ml 소환

**Comment by jmg7173** [comment]
오오.. 이것은 뭔가요

**Comment by minhoryang** [comment]
@jmg7173 우리가 같이 할 거요!

**Comment by jmg7173** [comment]
그렇다면 웹페이지랑 알파서비스를 시작해야겠군요 ㄷㄷ
벌써 서비스라니
