### ISSUE TITLE
MyPage/Template Requirements

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#45]
# < 내 페이지 관리 >

**0. 회원가입 시 이름받기**
- [ ] 이름 어떻게 받을지 확실하게 정해요 #21 

**1.사진**
- [x]  사진 초기 업로드
- [x] 사진 변경
- [ ] 기본 이미지로 변경
- [ ] 사진이 정사각형이 아니면 짜부라지는 버그 수정 #35 

**2.아이디**
- [ ] 아이디 찾기

**3.패스워드**
- [ ] 패스워드 변경 #40 
- [ ] 패스워드 찾기 #43 

**4.휴대폰 번호**  #8 
- [ ] 번호 추가하기
- [ ] 번호 변경하기
- [ ] 번호 삭제하기

**5.이메일** #6 
- [ ] 이메일 추가하기
- [ ] 이메일 변경하기
- [ ] 이메일 삭제하기

**6.별명관리**
- [ ] 자기별명 자기가 추천하기
- [x] 남이 추천해주면 내 페이지에 뜨기
  - [ ] 알림 받기 #42 
  - [ ] 추천된 닉네임을 다른 사용자들이 ‘좋아요’ 하기 #18 
  - [x] 추천된 닉네임을 사용자가 직접 추가하기
  - [ ] 추천총량 분석 #19 

**7.탈퇴** #44 
- [ ] 탈퇴하기 기능 추가
- [ ] 탈퇴시 설문조사 기능
# <템플렛 / UI>

**0.템플릿 다시 짜기**
- [ ] 재사용 가능한 규칙적인 상속구조 설계 #41 

**1.검색창 기능**
- [ ] 친구 이름 자동완성 #27 

**2.에러메시지 UI 수정**
- [ ] 에러메시지가 UI 안에서 나오지 않음 #39

**Comment by yunitto** [comment]
REQUIREMENTS.md 로 다시 수정할게요!
