### ISSUE TITLE
기능 총 정리 / 완료체크

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#47]
## **구현 완료된 기능은 체크해주세요.**
# <시급한 임무 TOP 5>
- [x] [#41](https://github.com/minhoryang/AwesomeTitle/issues/41) 템플릿 재구성(재사용 가능한 규칙적인 상속구조 설계)
- [x] [#21](https://github.com/minhoryang/AwesomeTitle/issues/21) 이름 어떻게 받을지 확실하게 정하기
- [x] [#46](https://github.com/minhoryang/AwesomeTitle/issues/46) 사진 없이 submit을 누르면 빈 이미지가 등록되는 버그

---
# <내 페이지 관리>

**0. 회원가입**
- [x] [#48](https://github.com/minhoryang/AwesomeTitle/issues/48) 회원가입 시 아이디 중복 알림의 불편사항 개선 
- [ ] 이메일 인증을 위한 이메일 기입 필요.

**1.사진**
- [x] #49 기본 이미지로 변경하는게 있으면 좋겠습니다
- [x] [#35](https://github.com/minhoryang/AwesomeTitle/issues/35) 사진이 정사각형이 아니면 찌그러지는 버그 수정 

**2.아이디**
- [ ] 아이디 찾기

**3.패스워드**
- [x] [#40](https://github.com/minhoryang/AwesomeTitle/issues/40) 패스워드 변경
- [ ] [#43](https://github.com/minhoryang/AwesomeTitle/issues/43) 패스워드 찾기

**4.휴대폰 번호** [#8](https://github.com/minhoryang/AwesomeTitle/issues/8) 
- [ ] 번호 추가하기
- [ ] 번호 변경하기
- [ ] 번호 삭제하기

**5.이메일** [#6](https://github.com/minhoryang/AwesomeTitle/issues/6)
- [ ] 이메일 추가하기
- [ ] 이메일 변경하기
- [ ] 이메일 삭제하기

**6.별명관리**
- [x] 자기 별명을 자기가 추천할지 말지 정해야합니다.
- [x] [#42](https://github.com/minhoryang/AwesomeTitle/issues/42) 별명추천하면 알림 받기
- [ ] [#18](https://github.com/minhoryang/AwesomeTitle/issues/18) 추천된 닉네임을 다른 사용자들이 ‘좋아요’ 하기  
- [ ] [#19](https://github.com/minhoryang/AwesomeTitle/issues/19) 추천총량 분석/1등만 보여주기

**7.탈퇴** [#44](https://github.com/minhoryang/AwesomeTitle/issues/44)
- [x] 탈퇴하기 기능 추가
- [ ] 탈퇴시 설문조사 기능

---
# <템플렛 / UI>

**1.검색창 기능**
- [ ] [#27](https://github.com/minhoryang/AwesomeTitle/issues/27) 친구 이름 자동완성

**2.에러메시지 UI 수정**
- [x] [#39](https://github.com/minhoryang/AwesomeTitle/issues/39) 에러메시지가 UI 안에서 나오지 않음

**3.메인화면(첫페이지) 디자인**
- [ ] [#31](https://github.com/minhoryang/AwesomeTitle/issues/31) 생일인 사람 표시기능

---
# <업적 관리>

**0.업적이 뭘까**
- [x] [#29](https://github.com/minhoryang/AwesomeTitle/issues/29) 업적을 정하는 회의
- [ ] [#30](https://github.com/minhoryang/AwesomeTitle/issues/30) 업적 랭킹 기능

**Comment by minhoryang** [comment]
우와아아우!!!!!!! 최고에요!!!!! WeeklyMeeting 하는 느낌!

**Comment by juice500ml** [comment]
#46 3687b09c0d76af72373cbbee3c0d5918e266014b
#35 7b1a1603be21745b2309ca35df689a174bc66714

근데 왜 jmg7173 커밋으로 뜨는거짘ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
# 아이디 / 비밀번호 찾기

회원가입에서 받은 정보만으로 찾아 주어야 하기 때문에, 생각을 조금 더 해봐야합니다.
- 방법 1. 질의 응답ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
  - A. 질문도 응답도 직접쓰게해서ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
    - 안됨. 이젠 질의응답 찾기 기능 만들어야함.ㅜㅠ
  - B. 질문을 우리가 만들자?
- 방법 2. 이메일 인증을 통해서 찾자!
  ### 그러면 회원가입에 이메일 하나를 꼭 넣고, 인증과정을 넣어야함.
- 방법 3. 연대책임 제도 : 추천인을 가입할 때 기입해서, 그사람통해서 찾아야함?
- 방법 4. Face to Face 제도 : 비밀번호 찾기를 할 때 주변에 있는 아무나를 붙잡고, 그사람에게 푸시를 보내줍시다. **굳굳ㄷ?**
- 방법 5. Face to Face to Face to Face to Face to ... 제도: 다단계방식으로 랜덤의 새 비밀번호를 한글자씩 공개.

*\* 무언가 엄청나게 재밌어서 비밀번호 찾기를 하고 싶어지는 무언가 *\* 가 있었으면 좋겠음.

## 결론

우선 이메일로 합시다!

**Comment by minhoryang** [comment]
# 주소록 기능
- 휴대폰
- 이메일?
- 생일
- 등...
- 어디에서 뭘 하고 있는지?
- 릴리즈 몇기인지? (기수안셈...ㅠㅠ)
- 언제 가입했는지?
- 학번? 과? 전과?
- abeek 포기 기념일
- 과목 수강 기록
- **환 교수 *회 수강
- **환 교수 연속 *회 수강
- 재수강 *회
- FA *회

### 이 부분은 그래서 회의가 더 필요합니다.

 주소록보다 업적을 먼저 만들고 싶다는 의견이 많음 @yunitto @juice500ml @minhoryang
이 이슈를 미루는 것으로 하죠!
새 마일스톤을 만듭시다!

**Comment by minhoryang** [comment]
# 이 부분은 업적에 넣겠습니다.
- 과목 수강 기록
- **환 교수 *회 수강
- **환 교수 연속 *회 수강
- 재수강 *회
- FA *회
- ACMICPC 푼 문제 100문제 달성!
- ACMICPC 푼 문제 1000문제 달성!

**Comment by minhoryang** [comment]
이메일도 주소록이라고 생각하고, 만약, 회원가입 간소화 + 비밀번호찾기 설문에서 필요 없으면, 이메일은 그냥 주소록 할 때 쓸 것.

**Comment by minhoryang** [comment]
## 별명관리
- "자기 별명을 자기가 추천할지 말지 정해야합니다."
  - 민교가 너무 디펜스하고있음
  - 내가 추가하고 싶은 별명을 다른 사람이 내 프로필 페이지에 들어와서 허가해 줘야 한다면? @minhoryang
    - 좋아요기능이 먼저 있어야 함.
    - 싫어요기능도 있어야함... ㅠㅠ

**Comment by minhoryang** [comment]
## TODO

다음의 기획안을 WIKI에 만들어서 기능을 다 같이 만들어보죠
- 비번찾기
- 별명 좋아요/싫어요
- 업적
- 주소록
- 통계
- 알림

**Comment by minhoryang** [comment]
회의 끝났습니다!

**Comment by yunitto** [comment]
구현도 많이 됐고 Milestone으로 잘 정리가 되어있으니 이슈 닫겠습니다!

**Comment by minhoryang** [comment]
고마워요!!! 앞으로는 위키에 회의록이랑 같이 넣을까요?

**Comment by yunitto** [comment]
넵넵 위키가 훨씬 편하고 보기 좋아요! 위키를 적극 활용합시다!!!!
